name: Prebuild libvpx (VS2019 v142, x86-windows-static, /MT)

on:
  workflow_dispatch:

jobs:
  libvpx-x86:
    runs-on: windows-2022
    env:
      VCPKG_PLATFORM_TOOLSET: v142   # force VS2019 toolset
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure v142 toolset (install if missing)
        shell: pwsh
        run: |
          $vsInstaller = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vs_installer.exe"
          $vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
          $hasV142 = & $vswhere -products * -requires Microsoft.VisualStudio.Component.VC.v142.x86.x64 -property installationPath
          if (-not $hasV142) {
            Write-Host "Installing VS2019 v142 toolset..."
            $vsPath = & $vswhere -products * -latest -property installationPath
            & $vsInstaller modify --installPath "$vsPath" --add Microsoft.VisualStudio.Component.VC.v142.x86.x64 --quiet --norestart --nocache
            if ($LASTEXITCODE -ne 0) { throw "Failed to install v142 toolset." }
          }
          Write-Host "v142 is available."

      - name: Clone vcpkg
        run: git clone --depth 1 https://github.com/microsoft/vcpkg.git

      - name: Bootstrap vcpkg
        run: .\vcpkg\bootstrap-vcpkg.bat -disableMetrics

      - name: Install libvpx (x86-windows-static, /MT)
        run: .\vcpkg\vcpkg.exe install libvpx:x86-windows-static --clean-after-build

      - name: Collect library
        shell: pwsh
        run: |
          $libDir = Join-Path $env:VCPKG_INSTALLATION_ROOT "installed\x86-windows-static\lib"
          if (!(Test-Path $libDir)) { throw "vcpkg lib folder not found: $libDir" }
          New-Item -ItemType Directory -Force -Path artifacts\x86-windows-static | Out-Null
          Copy-Item "$libDir\vpx.lib" "artifacts\x86-windows-static\vpx.lib"
          Copy-Item "$libDir\vpx.lib" "artifacts\x86-windows-static\vpxmt.lib"  # legacy filename if needed

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: libvpx-v142-x86-windows-static
          path: artifacts/x86-windows-static/*
